# Generated by Django 6.0.3 on 2026-03-23 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('home_anniversary', models.DateField(blank=True, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='US', max_length=100)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('language_preference', models.CharField(default='en', max_length=10)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('any', 'Any')], default='any', max_length=10)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('opted_out_email', models.BooleanField(default=False)),
                ('opted_out_sms', models.BooleanField(default=False)),
                ('contact_type', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active_buyer', 'Active Buyer'), ('active_seller', 'Active Seller'), ('under_contract', 'Under Contract'), ('past_client', 'Past Client'), ('sphere', 'Sphere of Influence'), ('referral_partner', 'Referral Partner'), ('vendor', 'Vendor'), ('investor', 'Investor'), ('renter', 'Renter'), ('landlord', 'Landlord'), ('other', 'Other')], default='lead', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('zillow', 'Zillow'), ('realtor_com', 'Realtor.com'), ('facebook', 'Facebook / Instagram'), ('google', 'Google Ads'), ('open_house', 'Open House'), ('referral', 'Referral'), ('sphere', 'Sphere / Manual Entry'), ('sign_call', 'Sign Call'), ('cold_call', 'Cold Call'), ('text_inquiry', 'Text Inquiry'), ('event', 'Event'), ('qr_code', 'QR Code'), ('import', 'CSV Import'), ('other', 'Other')], default='other', max_length=20)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('children_info', models.TextField(blank=True)),
                ('interests_hobbies', models.TextField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_instagram', models.CharField(blank=True, max_length=100)),
                ('buyer_seller_type', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Buyer & Seller'), ('investor', 'Investor'), ('renter', 'Renter')], max_length=10)),
                ('is_first_time_buyer', models.BooleanField(blank=True, null=True)),
                ('financing_status', models.CharField(choices=[('unknown', 'Unknown'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pre_approved', 'Pre-Approved'), ('cash', 'Cash')], default='unknown', max_length=20)),
                ('lender_name', models.CharField(blank=True, max_length=200)),
                ('lender_contact', models.CharField(blank=True, max_length=200)),
                ('pre_approval_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('desired_bedrooms_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('desired_bathrooms_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('desired_sqft_min', models.PositiveIntegerField(blank=True, null=True)),
                ('desired_sqft_max', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_areas', models.TextField(blank=True, help_text='Neighborhoods, towns, zip codes')),
                ('must_haves', models.TextField(blank=True)),
                ('deal_breakers', models.TextField(blank=True)),
                ('target_move_date', models.DateField(blank=True, null=True)),
                ('current_home_situation', models.TextField(blank=True)),
                ('timeline_urgency', models.CharField(choices=[('immediate', 'Immediate (0–3 months)'), ('short', 'Short-Term (3–6 months)'), ('medium', 'Medium-Term (6–12 months)'), ('long', 'Long-Term (12+ months)'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('motivation_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Just browsing'), (2, '2'), (3, '3'), (4, '4'), (5, '5 – Moderately motivated'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10 – Must move now')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='contacts.contact')),
                ('spouse_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='contacts.contact')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.contact')),
            ],
            options={
                'ordering': ['-is_primary', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('call', 'Call'), ('text', 'Text'), ('email', 'Email'), ('meeting', 'Meeting'), ('showing', 'Showing'), ('open_house', 'Open House'), ('task', 'Task'), ('system', 'System Event')], default='general', max_length=20)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('label', models.CharField(choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='mobile', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_text', models.BooleanField(default=True)),
                ('can_call', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.contact')),
            ],
            options={
                'ordering': ['-is_primary', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.tag'),
        ),
    ]
