# Generated by Django 6.0.1 on 2026-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnote',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='call_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('answered', 'Answered'), ('voicemail', 'Left Voicemail'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('left_message', 'Left Message'), ('wrong_number', 'Wrong Number')], max_length=15),
        ),
        migrations.AddField(
            model_name='contactnote',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
