# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations
from django.contrib.auth.hashers import make_password


TEST_EMAIL = "test@render.local"
TEST_PASSWORD = "RenderTest123!"
TEST_FIRST_NAME = "Render"
TEST_LAST_NAME = "Tester"
TEST_ORG_NAME = "Render Test Workspace"


def seed_render_test_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    Organization = apps.get_model("organizations", "Organization")
    Membership = apps.get_model("organizations", "Membership")

    user, created = User.objects.get_or_create(
        email=TEST_EMAIL,
        defaults={
            "first_name": TEST_FIRST_NAME,
            "last_name": TEST_LAST_NAME,
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
        },
    )

    # Always reset to known credentials for predictable test access.
    user.first_name = TEST_FIRST_NAME
    user.last_name = TEST_LAST_NAME
    user.is_staff = True
    user.is_superuser = True
    user.is_active = True
    user.password = make_password(TEST_PASSWORD)
    user.save(
        update_fields=[
            "first_name",
            "last_name",
            "is_staff",
            "is_superuser",
            "is_active",
            "password",
        ]
    )

    org, _ = Organization.objects.get_or_create(
        name=TEST_ORG_NAME,
        defaults={
            "owner": user,
            "org_type": Organization.OrgType.INDIVIDUAL,
            "plan": Organization.Plan.FREE,
            "is_active": True,
        },
    )
    if org.owner_id != user.id:
        org.owner = user
        org.is_active = True
        org.save(update_fields=["owner", "is_active", "updated_at"])

    Membership.objects.update_or_create(
        user=user,
        organization=org,
        defaults={
            "role": Membership.Role.OWNER,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_render_test_user, migrations.RunPython.noop),
    ]
