# Generated by Django 6.0.3 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_initial"),
        ("properties", "0002_initial"),
        ("users", "0002_seed_render_test_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPublicProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("is_published", models.BooleanField(default=False)),
                ("page_title", models.CharField(blank=True, max_length=180)),
                ("agent_display_name", models.CharField(blank=True, max_length=180)),
                ("agent_headline", models.CharField(blank=True, max_length=180)),
                ("agent_bio", models.TextField(blank=True)),
                ("agent_photo", models.ImageField(blank=True, null=True, upload_to="public_profiles/agent_photos/")),
                ("broker_name", models.CharField(blank=True, max_length=180)),
                ("broker_logo", models.ImageField(blank=True, null=True, upload_to="public_profiles/broker_logos/")),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("office_address", models.CharField(blank=True, max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_public_profiles", to="organizations.organization"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="public_profiles", to="users.user")),
            ],
            options={
                "ordering": ["organization", "user"],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="PublicListingCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mls_id", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("coming_soon", "Coming Soon"),
                            ("closed", "Closed"),
                            ("off_market", "Off Market"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("beds", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("baths", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("sqft", models.PositiveIntegerField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True)),
                ("details_url", models.URLField(blank=True)),
                ("short_description", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="public_listing_cards", to="properties.property")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listing_cards", to="users.agentpublicprofile")),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
                "indexes": [
                    models.Index(fields=["profile", "is_active"], name="users_publi_profile_583afa_idx"),
                    models.Index(fields=["profile", "status"], name="users_publi_profile_e6f998_idx"),
                ],
                "unique_together": {("profile", "mls_id")},
            },
        ),
    ]
