# Generated by Django 6.0.3 on 2026-03-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agentpublicprofile_publiclistingcard'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publiclistingcard',
            new_name='users_publi_profile_d9da11_idx',
            old_name='users_publi_profile_583afa_idx',
        ),
        migrations.RenameIndex(
            model_name='publiclistingcard',
            new_name='users_publi_profile_6a4b9e_idx',
            old_name='users_publi_profile_e6f998_idx',
        ),
    ]
