# Generated by Django 6.0.3 on 2026-03-24 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_complianceexport'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='compliance__organiz_e2c35f_idx',
            old_name='compliance_a_organiz_8a85ea_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='compliance__organiz_ae1a25_idx',
            old_name='compliance_a_organiz_856180_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='compliance__organiz_20bfce_idx',
            old_name='compliance_a_organiz_8d8a39_idx',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='complianceexport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='compliancepolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
    ]
