# Generated by Django 6.0.3 on 2026-03-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_complianceexport_artifact_fields'),
        ('compliance', '0003_rename_compliance_a_organiz_8a85ea_idx_compliance__organiz_e2c35f_idx_and_more'),
    ]

    operations = [
    ]
