# Generated by Django 6.0.3 on 2026-03-24 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contactnote_call_direction_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCaptureForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Internal name for this form', max_length=200)),
                ('form_type', models.CharField(choices=[('buyer', 'Buyer Inquiry'), ('seller', 'Seller / Home Valuation'), ('general', 'General Contact'), ('open_house', 'Open House Sign-in'), ('valuation', 'Home Valuation Request'), ('investment', 'Investor Inquiry')], default='general', max_length=20)),
                ('contact_source', models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook / Instagram'), ('google', 'Google Ads'), ('other', 'Other')], default='website', help_text='Source tag applied to contacts created by this form', max_length=20)),
                ('headline', models.CharField(default='Get in touch', max_length=200)),
                ('subheadline', models.TextField(blank=True, help_text='Optional intro text shown above the form')),
                ('button_text', models.CharField(default='Submit', max_length=80)),
                ('thank_you_title', models.CharField(default='Thank you!', max_length=200)),
                ('thank_you_body', models.TextField(default='We received your info and will be in touch shortly.')),
                ('redirect_url', models.URLField(blank=True, help_text='If set, redirect here after submission instead of showing the thank-you message.')),
                ('show_phone', models.BooleanField(default=True)),
                ('show_message', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=False, help_text='Property address of interest')),
                ('show_budget', models.BooleanField(default=False)),
                ('show_timeline', models.BooleanField(default=False)),
                ('require_phone', models.BooleanField(default=False)),
                ('require_message', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='New contacts from this form are assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_forms', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False, help_text='True when a Contact record was successfully created')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_submissions', to='contacts.contact')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lead_forms.leadcaptureform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
