# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('lead_forms', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcaptureform',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='New contacts from this form are assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcaptureform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_submissions', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='leadformsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lead_forms.leadcaptureform'),
        ),
    ]
