# Generated by Django 6.0.3 on 2026-03-25 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional title; defaults to the address.', max_length=255)),
                ('event_type', models.CharField(choices=[('public', 'Public Open House'), ('broker_only', 'Broker Open'), ('private', 'Private Showing'), ('virtual', 'Virtual Open House')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sign_in_message', models.TextField(blank=True, help_text='Optional welcome message shown on the public sign-in page.')),
                ('notes', models.TextField(blank=True)),
                ('followup_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='OpenHouseVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('visitor_type', models.CharField(choices=[('buyer', 'Buyer'), ('neighbor', 'Neighbor'), ('agent', 'Agent / Realtor'), ('investor', 'Investor'), ('renter', 'Renter'), ('other', 'Other')], default='buyer', max_length=15)),
                ('is_pre_approved', models.BooleanField(default=False)),
                ('pre_approval_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('represented_by_agent', models.BooleanField(default=False, help_text='Is this buyer already working with an agent?')),
                ('agent_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('signed_in_at', models.DateTimeField(auto_now_add=True)),
                ('followed_up', models.BooleanField(default=False)),
                ('followed_up_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['signed_in_at'],
            },
        ),
    ]
