# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Defaults to contact name if blank.', max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated deal value or commission.', max_digits=12, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('lost_reason', models.TextField(blank=True)),
                ('entered_stage_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('pipeline_type', models.CharField(choices=[('lead', 'Lead'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('recruiting', 'Recruiting'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-assigned to new contacts of the matching type.')),
            ],
            options={
                'ordering': ['pipeline_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('probability', models.PositiveSmallIntegerField(default=0, help_text='Likelihood of closing (0–100%).')),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('expected_days', models.PositiveSmallIntegerField(blank=True, help_text='Expected days a deal stays in this stage.', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('required_tasks', models.JSONField(blank=True, default=list, help_text='List of task definitions to create/check on stage entry. Example: [{"title":"Send disclosure","task_type":"document","due_in_days":0,"priority":"high"}]')),
                ('required_form_ids', models.JSONField(blank=True, default=list, help_text='List of LeadCaptureForm IDs required for this stage.')),
                ('required_automation_rule_ids', models.JSONField(blank=True, default=list, help_text='List of AutomationRule IDs that must be active for this stage.')),
                ('enforce_requirements', models.BooleanField(default=False, help_text='When enabled, block stage moves if form/automation requirements are unmet.')),
            ],
            options={
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
