# Generated by Django 6.0.1 on 2026-03-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('school_district', models.CharField(blank=True, max_length=100)),
                ('mls_number', models.CharField(blank=True, max_length=50)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('condo', 'Condo / Co-op'), ('townhouse', 'Townhouse'), ('multi_family', 'Multi-Family'), ('land', 'Land / Lot'), ('commercial', 'Commercial'), ('mobile_home', 'Mobile / Manufactured'), ('new_construct', 'New Construction'), ('other', 'Other')], default='single_family', max_length=20)),
                ('status', models.CharField(choices=[('off_market', 'Off Market'), ('coming_soon', 'Coming Soon'), ('active', 'Active'), ('pending', 'Pending'), ('under_contract', 'Under Contract'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='off_market', max_length=20)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original_list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hoa_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly HOA fee', max_digits=8, null=True)),
                ('bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms_full', models.SmallIntegerField(blank=True, null=True)),
                ('bathrooms_half', models.SmallIntegerField(blank=True, null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('lot_size_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('garage_spaces', models.SmallIntegerField(blank=True, null=True)),
                ('year_built', models.SmallIntegerField(blank=True, null=True)),
                ('stories', models.SmallIntegerField(blank=True, null=True)),
                ('list_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('lockbox_type', models.CharField(choices=[('none', 'None'), ('combo', 'Combo'), ('supra', 'Supra'), ('bluetooth', 'Bluetooth'), ('other', 'Other')], default='none', max_length=15)),
                ('lockbox_code', models.CharField(blank=True, max_length=50)),
                ('showing_instructions', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('is_active', models.BooleanField(default=True)),
                ('listing_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('owner_contact', models.ForeignKey(blank=True, help_text='Contact record for the property owner/seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='contacts.contact')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_notes', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.SmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['organization', 'status'], name='properties__organiz_9ce208_idx'),
        ),
    ]
