# Generated by Django 6.0.1 on 2026-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyphoto',
            options={'ordering': ['-is_primary', 'order', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
