# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('financing', 'Financing'), ('title', 'Title'), ('closing', 'Closing'), ('post_close', 'Post-Close'), ('other', 'Other')], default='other', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('na', 'N/A'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('disclosure', 'Disclosure'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('financing', 'Financing'), ('title', 'Title'), ('closing', 'Closing'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='transactions/documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_address', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase (Buyer)'), ('listing', 'Listing (Seller)'), ('dual', 'Dual Agency'), ('lease', 'Lease / Rental')], default='purchase', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('clear_to_close', 'Clear to Close'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('fallen_through', 'Fallen Through'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('financing_type', models.CharField(choices=[('conventional', 'Conventional'), ('fha', 'FHA'), ('va', 'VA'), ('usda', 'USDA'), ('jumbo', 'Jumbo'), ('cash', 'Cash'), ('other', 'Other')], default='conventional', max_length=15)),
                ('mls_number', models.CharField(blank=True, max_length=50)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('earnest_money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('earnest_money_due', models.DateField(blank=True, null=True)),
                ('earnest_received', models.BooleanField(default=False)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage (e.g. 3.00)', max_digits=4, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lender_name', models.CharField(blank=True, max_length=200)),
                ('lender_contact', models.CharField(blank=True, max_length=200)),
                ('lender_email', models.EmailField(blank=True, max_length=254)),
                ('lender_phone', models.CharField(blank=True, max_length=30)),
                ('title_company', models.CharField(blank=True, max_length=200)),
                ('title_officer', models.CharField(blank=True, max_length=200)),
                ('title_email', models.EmailField(blank=True, max_length=254)),
                ('title_phone', models.CharField(blank=True, max_length=30)),
                ('closing_attorney', models.CharField(blank=True, max_length=200)),
                ('closing_email', models.EmailField(blank=True, max_length=254)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('inspection_deadline', models.DateField(blank=True, null=True)),
                ('inspection_objection_deadline', models.DateField(blank=True, null=True)),
                ('inspection_resolution_deadline', models.DateField(blank=True, null=True)),
                ('appraisal_deadline', models.DateField(blank=True, null=True)),
                ('financing_deadline', models.DateField(blank=True, null=True)),
                ('title_deadline', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('inspection_completed', models.BooleanField(default=False)),
                ('appraisal_completed', models.BooleanField(default=False)),
                ('financing_approved', models.BooleanField(default=False)),
                ('title_clear', models.BooleanField(default=False)),
                ('final_walkthrough_done', models.BooleanField(default=False)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buyer_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_transactions', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
