# Generated by Django 6.0.3 on 2026-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('call', 'Call'), ('text', 'Text'), ('email', 'Email'), ('meeting', 'Meeting'), ('document', 'Document'), ('follow_up', 'Follow-Up'), ('showing', 'Showing'), ('open_house', 'Open House'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('other', 'Other')], default='follow_up', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('snoozed', 'Snoozed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='none', max_length=15)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, help_text='What happened? Result of the call, outcome of the meeting, etc.')),
            ],
            options={
                'ordering': ['due_date', 'due_time', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('call', 'Call'), ('text', 'Text'), ('email', 'Email'), ('meeting', 'Meeting'), ('document', 'Document'), ('follow_up', 'Follow-Up'), ('showing', 'Showing'), ('open_house', 'Open House'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('other', 'Other')], default='follow_up', max_length=20)),
                ('title_template', models.CharField(help_text='Use {contact_name}, {agent_name} as merge fields.', max_length=255)),
                ('description_template', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('due_days_offset', models.SmallIntegerField(default=1, help_text='Days from trigger date when this task becomes due. Use 0 for same day.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
