# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='sent', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('category', models.CharField(choices=[('buyer_lead', 'Buyer Lead'), ('seller_lead', 'Seller Lead'), ('open_house', 'Open House'), ('past_client', 'Past Client'), ('sphere', 'Sphere / Referral'), ('transaction', 'Transaction'), ('nurture', 'Long-Term Nurture'), ('general', 'General')], default='general', max_length=20)),
                ('enroll_contact_type', models.CharField(blank=True, help_text='Optional contact type filter for automatic enrollment.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DripCampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('delay_days', models.PositiveSmallIntegerField(default=0, help_text='Days to wait before this step runs after the previous step.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['campaign', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS / Text'), ('call_script', 'Call Script')], default='email', max_length=15)),
                ('category', models.CharField(choices=[('buyer_lead', 'Buyer Lead'), ('seller_lead', 'Seller Lead'), ('open_house', 'Open House'), ('past_client', 'Past Client'), ('sphere', 'Sphere / Referral'), ('transaction', 'Transaction'), ('nurture', 'Long-Term Nurture'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line (email templates only)', max_length=255)),
                ('body', models.TextField(help_text='Use {{first_name}}, {{last_name}}, {{full_name}}, {{address}}, {{agent_name}}, {{closing_date}}, {{price}} as merge fields.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template_type', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=15)),
                ('last_step_order', models.PositiveSmallIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='contacts.contact')),
            ],
            options={
                'ordering': ['next_run_at', 'created_at'],
            },
        ),
    ]
