# Generated by Django 6.0.1 on 2026-03-24 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS / Text'), ('call_script', 'Call Script')], default='email', max_length=15)),
                ('category', models.CharField(choices=[('buyer_lead', 'Buyer Lead'), ('seller_lead', 'Seller Lead'), ('open_house', 'Open House'), ('past_client', 'Past Client'), ('sphere', 'Sphere / Referral'), ('transaction', 'Transaction'), ('nurture', 'Long-Term Nurture'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line (email templates only)', max_length=255)),
                ('body', models.TextField(help_text='Use {{first_name}}, {{last_name}}, {{full_name}}, {{address}}, {{agent_name}}, {{closing_date}}, {{price}} as merge fields.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['template_type', 'category', 'name'],
            },
        ),
    ]
