# Generated by hand on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
        ("message_templates", "0002_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeBroadcast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], default="email", max_length=10)),
                ("filter_contact_type", models.CharField(blank=True, help_text="Optional filter by contact type.", max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("completed", "Completed"), ("partial", "Completed With Failures"), ("failed", "Failed")], default="draft", max_length=15)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("launched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="one_time_broadcasts_created", to=settings.AUTH_USER_MODEL)),
                ("filter_assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="one_time_broadcast_filters", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="one_time_broadcasts", to="message_templates.messagetemplate")),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="OneTimeBroadcastDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped")], default="sent", max_length=10)),
                ("detail", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("broadcast", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="message_templates.onetimebroadcast")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="one_time_broadcast_deliveries", to="contacts.contact")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("broadcast", "contact")},
            },
        ),
    ]
