# Generated by hand on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message_templates", "0003_onetimebroadcast_onetimebroadcastdelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimebroadcast",
            name="approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="one_time_broadcasts_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="onetimebroadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("partial", "Completed With Failures"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
