# Generated by hand on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
        ("message_templates", "0004_onetimebroadcast_approval_and_schedule"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudienceSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("contact_type", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("inactive_days", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audience_segments", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
                ("tags", models.ManyToManyField(blank=True, related_name="audience_segments", to="contacts.tag")),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="filter_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="filter_inactive_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="filter_segment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="broadcasts", to="message_templates.audiencesegment"),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="filter_state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="filter_tags",
            field=models.ManyToManyField(blank=True, related_name="one_time_broadcasts", to="contacts.tag"),
        ),
        migrations.AddField(
            model_name="onetimebroadcast",
            name="filter_zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
