# Generated by Django 6.0.3 on 2026-03-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("integration_type", models.CharField(choices=[("calendar", "Calendar"), ("mls", "MLS / IDX"), ("zillow", "Zillow"), ("voice", "Voice / Calling"), ("esign", "E-Sign / Docs")], max_length=20)),
                ("provider", models.CharField(choices=[("google", "Google"), ("outlook", "Outlook / Microsoft 365"), ("mls_generic", "MLS (Generic)"), ("zillow", "Zillow"), ("generic", "Generic")], max_length=20)),
                ("status", models.CharField(choices=[("disconnected", "Disconnected"), ("connecting", "Connecting"), ("connected", "Connected"), ("error", "Error")], default="disconnected", max_length=20)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("external_account_id", models.CharField(blank=True, max_length=255)),
                ("access_token_encrypted", models.TextField(blank=True)),
                ("refresh_token_encrypted", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
            ],
            options={
                "ordering": ["integration_type", "provider", "display_name", "created_at"],
                "indexes": [
                    models.Index(fields=["organization", "integration_type", "provider"], name="integrations_organiz_c86713_idx"),
                    models.Index(fields=["organization", "status", "is_active"], name="integrations_organiz_2f95ea_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_calendar_id", models.CharField(max_length=255)),
                ("remote_calendar_name", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_cursor", models.TextField(blank=True)),
                ("last_sync_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("connection", models.ForeignKey(limit_choices_to={"integration_type": "calendar"}, on_delete=django.db.models.deletion.CASCADE, related_name="calendar_states", to="integrations.integrationconnection")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calendar_sync_states", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-is_primary", "remote_calendar_name", "remote_calendar_id"],
                "unique_together": {("connection", "remote_calendar_id")},
            },
        ),
        migrations.CreateModel(
            name="ExternalCalendarEventMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(choices=[("task", "Task"), ("open_house", "Open House"), ("closing", "Closing")], max_length=20)),
                ("local_object_id", models.PositiveBigIntegerField()),
                ("remote_calendar_id", models.CharField(blank=True, max_length=255)),
                ("remote_event_id", models.CharField(max_length=255)),
                ("remote_etag", models.CharField(blank=True, max_length=255)),
                ("last_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True)),
                ("connection", models.ForeignKey(limit_choices_to={"integration_type": "calendar"}, on_delete=django.db.models.deletion.CASCADE, related_name="calendar_event_maps", to="integrations.integrationconnection")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["organization", "event_type", "local_object_id"], name="integrations_organiz_28d48e_idx")],
                "unique_together": {("connection", "remote_event_id"), ("connection", "event_type", "local_object_id")},
            },
        ),
        migrations.CreateModel(
            name="ListingSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remote_listing_id", models.CharField(max_length=255)),
                ("source_mls_number", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("synced", "Synced"), ("error", "Error")], default="pending", max_length=20)),
                ("payload_checksum", models.CharField(blank=True, max_length=128)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("connection", models.ForeignKey(limit_choices_to={"integration_type__in": ["mls", "zillow"]}, on_delete=django.db.models.deletion.CASCADE, related_name="listing_states", to="integrations.integrationconnection")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="listing_sync_states", to="properties.property")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["organization", "status"], name="integrations_organiz_234457_idx"),
                    models.Index(fields=["organization", "source_mls_number"], name="integrations_organiz_65b40a_idx"),
                ],
                "unique_together": {("connection", "remote_listing_id")},
            },
        ),
    ]
