# Generated by Django 6.0.3 on 2026-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_calendar_id', models.CharField(max_length=255)),
                ('remote_calendar_name', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_cursor', models.TextField(blank=True)),
                ('last_sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_primary', 'remote_calendar_name', 'remote_calendar_id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCalendarEventMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('task', 'Task'), ('open_house', 'Open House'), ('closing', 'Closing')], max_length=20)),
                ('local_object_id', models.PositiveBigIntegerField()),
                ('remote_calendar_id', models.CharField(blank=True, max_length=255)),
                ('remote_event_id', models.CharField(max_length=255)),
                ('remote_etag', models.CharField(blank=True, max_length=255)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_type', models.CharField(choices=[('calendar', 'Calendar'), ('mls', 'MLS / IDX'), ('zillow', 'Zillow'), ('voice', 'Voice / Calling'), ('esign', 'E-Sign / Docs')], max_length=20)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('outlook', 'Outlook / Microsoft 365'), ('mls_generic', 'MLS (Generic)'), ('zillow', 'Zillow'), ('generic', 'Generic')], max_length=20)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['integration_type', 'provider', 'display_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(choices=[('calendar_push', 'Calendar Push'), ('calendar_pull', 'Calendar Pull'), ('listing_sync', 'Listing Sync')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('command', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('success_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_listing_id', models.CharField(max_length=255)),
                ('source_mls_number', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('payload_checksum', models.CharField(blank=True, max_length=128)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
