# Generated by Django 6.0.3 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_type", models.CharField(choices=[("calendar_push", "Calendar Push"), ("calendar_pull", "Calendar Pull"), ("listing_sync", "Listing Sync")], max_length=30)),
                ("status", models.CharField(choices=[("success", "Success"), ("partial", "Partial"), ("failed", "Failed")], default="success", max_length=20)),
                ("command", models.CharField(blank=True, max_length=80)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("success_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="organizations.organization")),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["organization", "run_type", "started_at"], name="integrations_organiz_b76a82_idx"),
                    models.Index(fields=["organization", "status", "started_at"], name="integrations_organiz_1b5d90_idx"),
                ],
            },
        ),
    ]
