# Generated by Django 6.0.3 on 2026-03-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalcalendareventmap',
            new_name='integration_organiz_41b880_idx',
            old_name='integrations_organiz_28d48e_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationconnection',
            new_name='integration_organiz_19013c_idx',
            old_name='integrations_organiz_c86713_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationconnection',
            new_name='integration_organiz_6a5a96_idx',
            old_name='integrations_organiz_2f95ea_idx',
        ),
        migrations.RenameIndex(
            model_name='listingsyncstate',
            new_name='integration_organiz_7c213b_idx',
            old_name='integrations_organiz_234457_idx',
        ),
        migrations.RenameIndex(
            model_name='listingsyncstate',
            new_name='integration_organiz_a8d480_idx',
            old_name='integrations_organiz_65b40a_idx',
        ),
    ]
