# Generated by Django 6.0.3 on 2026-03-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationsyncrun'),
        ('integrations', '0002_rename_integrations_organiz_28d48e_idx_integration_organiz_41b880_idx_and_more'),
    ]

    operations = [
    ]
