# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0002_initial'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsyncstate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_sync_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalcalendareventmap',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='externalcalendareventmap',
            name='connection',
            field=models.ForeignKey(limit_choices_to={'integration_type': 'calendar'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_maps', to='integrations.integrationconnection'),
        ),
        migrations.AddField(
            model_name='calendarsyncstate',
            name='connection',
            field=models.ForeignKey(limit_choices_to={'integration_type': 'calendar'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_states', to='integrations.integrationconnection'),
        ),
        migrations.AddField(
            model_name='integrationsyncrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='listingsyncstate',
            name='connection',
            field=models.ForeignKey(limit_choices_to={'integration_type__in': ['mls', 'zillow']}, on_delete=django.db.models.deletion.CASCADE, related_name='listing_states', to='integrations.integrationconnection'),
        ),
        migrations.AddField(
            model_name='listingsyncstate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='listingsyncstate',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_sync_states', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['organization', 'integration_type', 'provider'], name='integration_organiz_19013c_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['organization', 'status', 'is_active'], name='integration_organiz_6a5a96_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcalendareventmap',
            index=models.Index(fields=['organization', 'event_type', 'local_object_id'], name='integration_organiz_41b880_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendareventmap',
            unique_together={('connection', 'event_type', 'local_object_id'), ('connection', 'remote_event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='calendarsyncstate',
            unique_together={('connection', 'remote_calendar_id')},
        ),
        migrations.AddIndex(
            model_name='integrationsyncrun',
            index=models.Index(fields=['organization', 'run_type', 'started_at'], name='integration_organiz_6ac7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsyncrun',
            index=models.Index(fields=['organization', 'status', 'started_at'], name='integration_organiz_e53f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='listingsyncstate',
            index=models.Index(fields=['organization', 'status'], name='integration_organiz_7c213b_idx'),
        ),
        migrations.AddIndex(
            model_name='listingsyncstate',
            index=models.Index(fields=['organization', 'source_mls_number'], name='integration_organiz_a8d480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingsyncstate',
            unique_together={('connection', 'remote_listing_id')},
        ),
    ]
