# Generated by Django 6.0.3 on 2026-03-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_merge_20260325_0700'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationsyncrun',
            new_name='integration_organiz_6ac7a6_idx',
            old_name='integrations_organiz_b76a82_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationsyncrun',
            new_name='integration_organiz_e53f2f_idx',
            old_name='integrations_organiz_1b5d90_idx',
        ),
    ]
